---
title: "investigatePSthreshold"
author: "Thea Van Rossum"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

library(lemon) # print tables nicely in knit result without explicit call to kable()
knit_print.data.frame <- lemon_print

knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  message=FALSE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
```


```{r}

resultsDir <-"~/Dropbox/PostDocBork/subspecies/toolDevelopment/testingSubpopr/inSilicoMock/results_metaSNV-minFilter/"

#resultsDir <-"~/Dropbox/PostDocBork/subspecies/pancreaticCancer/2016-06_data/subpopr/metaSNV_minFilter/"
distMeth <- "mann"

cutOffVals <- seq(from=0.25,to=0.95,by=0.01)

psCutOffs <- collectPSCutoffClusterResults(resultsDir = resultsDir, 
                                                    distMeth = distMeth, 
                                                    cutOffVals = cutOffVals)

```


```{r}
psCutOffs %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% ggplot( aes(x=cutOffVals,y=species,color=factor(nClus)))+geom_point()+
  facet_grid(oneClus~.,space = "free_y",scales="free_y")
```


```{r}
psCutOffs %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% ggplot( aes(x=cutOffVals,y=species,color=factor(nClus)))+geom_point()+
  geom_line(size=3,alpha=0.6)+theme_minimal()
```


```{r}
psCutOffs %>% filter(cutOffVals>0.25) %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% ggplot( aes(x=cutOffVals,y=species,color=factor(nClus)))+geom_point()+
  geom_line(size=3,alpha=0.6)+theme_minimal()
```


```{r}
psCutOffs %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% 
  ggplot( aes(x=cutOffVals,group=nClus,fill=factor(nClus)))+geom_bar(stat="count")

psCutOffs %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% 
  ggplot( aes(x=cutOffVals,group=nClus,fill=factor(nClus)))+geom_bar(stat="count",position = "dodge")
```

```{r fig.height=3}
psCutOffs %>% group_by(species) %>% mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% 
  ggplot( aes(x=cutOffVals,group=nClus))+geom_bar(stat="count",position = "dodge")+facet_grid(.~nClus)+geom_vline(xintercept = 0.8)
```


```{r fig.height=3}
psCutOffs %>% group_by(species) %>% 
  filter(cutOffVals>0.5)%>% 
  mutate(maxNclus = max(nClus), oneClus = max(nClus) == 1 ) %>% ungroup() %>% filter(!oneClus) %>% 
  ggplot( aes(x=cutOffVals,group=nClus))+geom_bar(stat="count",position = "dodge")+facet_grid(.~nClus)+geom_vline(xintercept = 0.8)
```
